<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Data\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Data\Goal.csv">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Data\GoalModifier.csv">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Data\Payment.csv">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Data\Student.csv">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
